jobs:
  build:
    docker:
      - image: gcr.io/outreahc-docker/wavfront-collector
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: docker commit 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
